### ISSUE TITLE
How to set boundaries or parent element? 

### ISSUE THREAD

**Issue by ClydeDz** [savanesoff/overdrag#10]
Hey @savanesoff ,

Cool project! Is it possible to set the parent element or boundaries where this can be dragged? 

I'm trying to get a draggable-resizable element over an image, so the boundaries should be the borders of the image. 

Thanks!

**Comment by savanesoff** [comment]
> Hey @savanesoff ,
> 
> Cool project! Is it possible to set the parent element or boundaries where this can be dragged? 
> 
> I'm trying to get a draggable-resizable element over an image, so the boundaries should be the borders of the image. 
> 
> Thanks!

Hey @ClydeDz 

I get what you mean, but at the moment no.
However, the alternative is to have a parent with an image set as its background. Pretty common pattern.

How that helps.

**Comment by ClydeDz** [comment]
Thanks for the prompt reply and for confirming!
